#!/usr/bin/env python
"""reward_reagg.py — offline re-aggregation of the arm-1 v2 rollouts under alternative match definitions (Step 7, 2026-09-11).

For each requested step, reload rollouts/<step>.jsonl from the v2 run (160 rollouts = 32 prompts x 5), recompute the NLI pair
matrix s(i,j) with reward_v2.Scorers (same models, chunker env, GPU), and aggregate the match term four ways:
    original   : final spec — Hungarian, no tau gate, credit = sum s, F_0.5(prec, recall) * (1 - 0.25*offset)
    tau045     : same but pairs with s < 0.45 dropped (the pre-final tau gate)
    zero_allok : original, but match := 0 for prompts whose 5 rollouts are ALL answer-correct
    prec_only  : Hungarian, no tau, match := prec = credit / n_steps (no recall, no F, order penalty kept)
Then R = 5*answer + 2*match + 1*format - 1*pun (pun/format/answer/gates from the dump — unchanged), and the share of within-group
|advantage| carried by the answer term = sum|5(a - mean_a)| / (that + sum|2(m - mean_m)|), exactly as in ARM1_V2_REPORT.md §4.
Also reports the fraction of groups whose R varies (std > 0) — the groups that can produce any gradient at all.
Writes grpo_arms/REWARD_REAGG.md. Per-pair NLI scores are NOT stored in the dumps, hence the recompute (GPU job, ~minutes).
"""
import json
import os
import statistics as st
import sys
from collections import defaultdict

import numpy as np
from scipy.optimize import linear_sum_assignment

REPO = "/scratch/sghos104/rlpt"
sys.path.insert(0, f"{REPO}/reward_redesign")
import reward_v2 as rv  # noqa: E402

RUN = f"{REPO}/grpo_arms/runs/arm1_3b_matchv2_final"
STEPS = [int(x) for x in os.environ.get("REAGG_STEPS", "40 80 120").split()]
TAU = 0.45


def aggregate(s, kept, n_steps, n_gold, variant):
    pairs, credit = [], 0.0
    if s.size:
        ri, ci = linear_sum_assignment(-s)
        for i, j in zip(ri, ci):
            v = float(s[i, j])
            if v <= 0.0 or (variant == "tau045" and v < TAU):
                continue
            pairs.append((kept[i], j)); credit += v
    prec, recall = credit / n_steps, credit / n_gold
    b2 = rv.BETA ** 2
    fb = (1 + b2) * prec * recall / (b2 * prec + recall) if (prec + recall) > 0 else 0.0
    offset = rv.order_offset(pairs, n_gold)
    if variant == "prec_only":
        return prec * (1.0 - rv.W_ORDER * offset)
    return fb * (1.0 - rv.W_ORDER * offset)


def main():
    S = rv.Scorers()
    lines = [f"# Reward re-aggregation of arm-1 v2 rollouts (steps {STEPS}) — generated by grpo_arms/reward_reagg.py", "",
             "NLI pair matrices recomputed with reward_v2.Scorers (deberta-xlarge-mnli, chunker env); gates, answer, format, pun taken from the dumps.",
             "answer share = Σ|5·(a−ā)| / (Σ|5·(a−ā)| + Σ|2·(m−m̄)|) within each prompt group (5 rollouts), averaged over groups with any variation;",
             "groups w/ signal = fraction of groups whose total R varies across the 5 rollouts (std > 0).", "",
             "| step | variant | mean match | mean R | answer share of \\|adv\\| | groups w/ signal | mixed-correctness groups |",
             "|---|---|---|---|---|---|---|"]
    for step in STEPS:
        path = f"{RUN}/rollouts/{step}.jsonl"
        if not os.path.exists(path):
            lines.append(f"| {step} | – | MISSING dump {path} | | | | |"); continue
        rows = [json.loads(l) for l in open(path)]
        groups = defaultdict(list)
        for r in rows:
            groups[r["input"]].append(r)
        variants = ("original", "tau045", "zero_allok", "prec_only")
        per_group = {v: [] for v in variants}
        n_mixed = 0
        for rs in groups.values():
            answers = [float(r["answer"]) for r in rs]
            all_ok = min(answers) == 1.0
            n_mixed += max(answers) != min(answers)
            matches = {v: [] for v in variants}
            for r in rs:
                gt = json.loads(r["gts"])
                gold = [rv.THINK_RE.sub("", g).strip() for g in gt["gold_steps"] if not rv.FINAL_RE.match(g.strip())]
                gold = [g for g in gold if g]
                if r.get("gated"):
                    for v in variants:
                        matches[v].append(0.0)
                    continue
                segs, _ = rv.split_steps(r["output"])
                n_steps, n_gold = max(1, len(segs)), max(1, len(gold))
                kept, dup = S.dedupe(segs)
                s = S.nli_matrix([segs[i] for i in kept], gold) if segs and gold else np.zeros((0, 0))
                for v in variants:
                    m = aggregate(s, kept, n_steps, n_gold, v)
                    if v == "zero_allok" and all_ok:
                        m = 0.0
                    matches[v].append(m)
            for v in variants:
                ms = matches[v]
                R = [5 * a + 2 * m + float(r["format"]) - float(r.get("pun", 0.0)) if not r.get("gated") else 0.0
                     for a, m, r in zip(answers, ms, rs)]
                ma, mm = st.mean(answers), st.mean(ms)
                va = sum(abs(5 * (a - ma)) for a in answers); vm = sum(abs(2 * (m - mm)) for m in ms)
                per_group[v].append((st.mean(ms), st.mean(R), (va / (va + vm)) if va + vm > 0 else None, st.pstdev(R) > 0))
        for v in variants:
            g = per_group[v]
            shares = [x[2] for x in g if x[2] is not None]
            lines.append(f"| {step} | {v} | {st.mean(x[0] for x in g):.3f} | {st.mean(x[1] for x in g):.2f} | "
                         f"{st.mean(shares) if shares else float('nan'):.2f} | {st.mean(x[3] for x in g):.2f} | {n_mixed}/{len(groups)} |")
        lines.append(f"| {step} | (recorded in dump: match {st.mean(float(r['match']) for r in rows):.3f}, R {st.mean(float(r['score']) for r in rows):.2f}) | | | | | |")
    lines += ["", "Reading: `original` reproduces the training-time match (compare with the recorded dump line; small differences = NLI nondeterminism on",
              "TF32). The answer share is the quantity that collapsed in v2 (.64 @1 → .03 @120 in ARM1_V2_REPORT §4). A variant that keeps the answer",
              "share high at steps 80–120 without reducing 'groups w/ signal' is the one that would have kept the answer gradient alive."]
    open(f"{REPO}/grpo_arms/REWARD_REAGG.md", "w").write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
